### ISSUE TITLE
Cannot get Instrumentation tests to run with androidx

### ISSUE THREAD

**Issue by mylesbennett** [pot8os/Kotlin-Espresso-sample#11]
I was wondering if you had run your instrumentation tests since migrating to androidx?
I'm getting:
"Test running failed: Instrumentation run failed due to 'Process crashed.'
Empty test suite."

If I reset to just before the androidx migrate commit, "git clean -dfx" then reopen in Android Studio, the tests run just fine.

I tried the solution for the related issue at https://github.com/pot8os/Kotlin-Espresso-sample/issues/7 but this didn't help. I didn't expect it to since it was posted before the migration to androidx.

**Comment by mylesbennett** [comment]
Found the problem. Tried to push a branch but don't have write access.
In app/build.gradle change:

testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
to:
testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

**Comment by pot8os** [comment]
@mylesbennett Thanks for your feedback! Can you make a pull request against the repo?

**Comment by pot8os** [comment]
#12
