### ISSUE TITLE
NoClassDefFoundError test with minifyEnabled

### ISSUE THREAD

**Issue by evgenru** [pot8os/Kotlin-Espresso-sample#13]
Add to app/build.gradle buildTypes this code:
        debug {
            minifyEnabled true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

Change 
android.support.test....AndroidJUnitRunner
to
androidx.test....AndroidJUnitRunner

All ok....

But when I add this in ApplicationTest.kt this code in any test:
        Log.e("-----TEST------", "asdasd\n222".split("\n").toString())

It's crack with issue:
java.lang.NoClassDefFoundError: kotlin/text/StringsKt

In .dex class kotlin.text.StringsKt present.... and have method split... but not work...

**Comment by pot8os** [comment]
Do you want to [shrink](https://developer.android.com/studio/build/shrink-code#gradle-shrinker) the code? I think the app code where it's under `main` dir should have a reference to `StringKt` as well.

**Comment by evgenru** [comment]
Yes, my app is large and not run without it.
I test it in this example and get failed tests too )
Can you help my resolv this issue? :)
