### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by tenSunFree** [pot8os/Kotlin-Espresso-sample#19]
Affected Device(s)
Answer︰HTC U11 with Android 9.0。

Describe the Bug:
Add a clear description about the problem.
Answer︰Division by zero
![2020-03-02_234618](https://user-images.githubusercontent.com/23090085/75692649-d2f62d80-5ce0-11ea-9bb0-2ecdf8d3b607.jpg)

Expected Behavior:
A clear description of what you expected to happen.
Answer︰Ibid

maybe you can add some judgment
![rrrrr](https://user-images.githubusercontent.com/23090085/75692940-41d38680-5ce1-11ea-93d8-62007f94dad5.jpg)

**Comment by pot8os** [comment]
@tenSunFree Thanks for your report! The purpose of this repository is **NOT** to make a perfect calculator but to show how we write tests that work as both unit tests and instrumentation tests. So feel free to create a pull request what you suggested, and much better if you add test cases about that as well. Thanks!
