### ISSUE TITLE
No tests were found: Empty test suite.

### ISSUE THREAD

**Issue by imGurpreetSK** [pot8os/Kotlin-Espresso-sample#7]
Everytime I'm trying to run espresso tests written in Kotlin, the process fails with error `Class not found: "net.pot8os.kotlintestsample.ApplicationTest"Empty test suite.`. The same is with all the kotlin classes under AndroidTest folder, for any project I've tried.

**Comment by pot8os** [comment]
Seems your environment is broken. I might help if you could describe how you run tests as much as possible. Make sure your Android Studio installs Kotlin plugin.

**Comment by Gokulapriya13** [comment]
Class not found: "net.pot8os.kotlintestsample.ApplicationTest"Empty test suite.

**Comment by jrcinco** [comment]
The fix on Android Studio is:
step 1.- Go to Run/Debug configuration
step 2.- Go to Android Tests section
step 3.- Remove the test configuration file with (-)
step 4.- Press Apply and OK
step 5.- Run the test again
